### ISSUE TITLE
I do not understand where the mod looks for altsaves.toml

### ISSUE THREAD

**Issue by ketsuban** [vswarte/eldenring_alt_saves#7] opened 2024-07-06 13:02 UTC
I have the following folder structure.
```
ELDEN RING
├ Game
│ └ ...
└ Mod Engine 2
  ├ configs
  │ ├ vanilla.toml
  │ ├ seamlesscoop.toml
  │ ├ reforged.toml
  │ └ reforged-seamlesscoop.toml
  ├ modengine2
  │ └ ...
  └ mods
    ├ Alt Saves
    │ └ eldenring_alt_saves.dll
    └ ...
```
I would like to configure the extension Alt Saves uses. Previously I put `altsaves.toml` in the `Alt Saves` folder alongside the DLL, but this seems to no longer work. The documentation is a little unclear where I should be putting it, since I don't understand what is meant by "the game directory immediately" and "the modengine2 mod folder itself".

**Comment by ketsuban** [comment] 2024-07-06 13:47
After some experimentation I found that putting it inside the `Game` folder alongside `eldenring.exe` works, so I'm guessing that's "the game directory immediately". The following locations had no effect:

* In `ELDEN RING\Mod Engine 2`, alongside `modengine2_launcher.exe`
* In `ELDEN RING\Mod Engine 2\mods`
* In `ELDEN RING\Mod Engine 2\mods\Alt Saves`, alongside `eldenring_alt_saves.dll`
* In `ELDEN RING\Mod Engine 2\configs`

**Comment by vswarte** [comment] 2024-07-06 21:02
Hi, the `Game/altsaves.toml` should work but it should work if you put it directly in any of the folders references in the `mods` array of the `eldenring_alt_saves.dll`

**Comment by coxmelmoe** [comment] 2024-07-21 06:00
I also find this problem. If altsaves.toml doesn't locate in `Game`  folder, your saves folder only create `.mod` rather than   extension set in `.toml`. So how can I deal with this？ Thanks for you！
![1](https://github.com/user-attachments/assets/afa1c4b1-6304-46c5-9838-5530b7c33031)
![2](https://github.com/user-attachments/assets/fa061ccd-341e-4423-8920-d0cdbb9b89a0)



> Hi, the `Game/altsaves.toml` should work but it should work if you put it directly in any of the folders references in the `mods` array of the `eldenring_alt_saves.dll`

**Comment by coxmelmoe** [comment] 2024-07-21 08:05
After a few attempts, I find that I need make a copy of `.toml`  and put it in `mod` folder to make it work.

**Comment by vswarte** [comment] 2024-07-21 10:01
Hmm, that's odd. Game folder should def work and I can't reproduce the issue you describe after a quick test (just works for me). The mods/ folder approach is for big overhaul mods and such.

For anyone else troubleshooting this, follow the docs first: https://github.com/vswarte/alt-saves?tab=readme-ov-file#configuration

Closing this issue since your issue seems resolved, gonna do some extensive testing soon :tm: and if something similar pops-up I'll create a new issue.

**Closed as completed by vswarte** 2024-07-21 10:01 UTC
